function(setup_component)
  #Set binary path
  file(RELATIVE_PATH TARGET_REL_PATH ${CMAKE_SOURCE_DIR}/src ${CMAKE_CURRENT_SOURCE_DIR})
  set(INCLUDE_DIRECTORY_SRC ${CMAKE_CURRENT_SOURCE_DIR}/include)
  set(INCLUDE_DIRECTORY_DST ${CMAKE_BINARY_DIR}/include/${TARGET_REL_PATH})
  message("INCLUDE_DIRECTORY_DST: ${INCLUDE_DIRECTORY_DST}")

  execute_process(
      COMMAND mkdir -p "${INCLUDE_DIRECTORY_DST}"
      COMMAND rm -r "${INCLUDE_DIRECTORY_DST}"
      COMMAND ln -sf "${INCLUDE_DIRECTORY_SRC}" "${INCLUDE_DIRECTORY_DST}" 
  )
endfunction()